### ISSUE TITLE
bug(admin): tsconfig target=ES2020 but code uses String.replaceAll (ES2021)

### ISSUE THREAD

**Issue by 100rd** [100rd/Omniscience#258]
## Bug

`apps/admin/tsconfig.json` targets `ES2020`, but `apps/admin/src/pages/IncidentTimelinePage.tsx` (introduced by #235 / PR #246) uses `String.prototype.replaceAll` on lines 137-138 — a method that requires ES2021+.

The bug is invisible during local TS dev (Vite + esbuild are permissive), but the production Docker build runs strict `tsc` and fails:

```
src/pages/IncidentTimelinePage.tsx(137,8): error TS2550:
  Property 'replaceAll' does not exist on type 'string'.
  Do you need to change your target library?
  Try changing the 'lib' compiler option to 'es2021' or later.
src/pages/IncidentTimelinePage.tsx(137,8): error TS2550: ...
target admin: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 2
```

## Impact

`docker compose up -d --build app admin` from the documented quick-start fails on the admin build step. **v0.5 is undeployable via the documented workflow** until this lands.

## Why CI didn't catch it

The CI workflow (`.github/workflows/ci.yml`) runs Python tooling (ruff, mypy, pytest) but does not build the admin Docker image. The admin TS strict-build only runs as part of the Dockerfile's `npm run build`.

## Reproduction

```bash
git checkout main
docker compose build admin
# → error TS2550 on IncidentTimelinePage.tsx:137
```

## Fix

Bump `tsconfig.json` target + lib from `ES2020` to `ES2021`. Modern browsers (anything ≥ 2021) support it natively. One-line change.

## Follow-ups (separate issues — not in scope of this fix)

- Add an `admin-build` job to `.github/workflows/ci.yml` so this class of regression is caught in CI, not at `docker compose up` time
- Audit other files for ES2021+ usage to make sure ES2021 is sufficient (`grep -rn "\.replaceAll\|Promise\.any\|String\.prototype\.at" apps/admin/src/`)
